views/products_route.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, flash, session
from models import *
from wtforms import Form,validators
from forms import AddForm, LoginForm
from flask_login import logout_user, login_required, UserMixin

products_blueprint = Blueprint('products_route', __name__)

@products_blueprint.route('/logout')  # User Logout
@login_required
def logout():
    form = LoginForm(request.form)
    logout_user()
    return render_template('login.html', form=form)

@products_blueprint.route('/all_products/<string:mail>') # Displays all products to  users
@login_required
def all_products(mail):
    data = Products.query.all()
    return render_template('display_products.html', data=data, mail=mail, title="Products")
        

@products_blueprint.route('/my_prods/<string:mail>') # Displays only users products  
@login_required
def my_products(mail):
    user = Users.query.filter_by(user_mail = mail).one()
    data = Products.query.filter(Products.ref_user.any(user_mail = mail)).all()
    return render_template("product_options.html", data=data, mail=mail)

@products_blueprint.route('/add_prod/<string:mail>', methods=['GET', 'POST'])  # Adds product
@login_required
def add(mail):
    form = AddForm(request.form)
    if request.method == 'POST' and form.validate():
        user = Users.query.filter_by(user_mail = mail).first()
        prod=Products(product_name=form.product_name.data, product_cost=form.product_cost.data, product_desc=form.product_desc.data)
        user.products.append(prod)
        db.session.commit()
        flash('Successfully added a product !')
        return redirect(url_for('products_route.my_products', mail=mail)) 
    return render_template('add_product.html', form = form, data=mail)

@products_blueprint.route('/delete/<string:mail>/<string:prod_name>', methods = ['GET']) # Deletes User product
@login_required
def delete(mail,prod_name):
    prod = Products.query.filter_by(product_name = prod_name).first()
    user = Users.query.filter_by(user_mail = mail).one()
    user.products.remove(prod)
    db.session.commit()
    flash("Record Has Been Deleted Successfully")
    return redirect(url_for('products_route.my_products', mail=mail))

@products_blueprint.route('/edit/<string:mail>/<string:prod_name>', methods =['GET']) #Edit User Product
@login_required
def edit(mail, prod_name):
    user = Users.query.filter_by(user_mail = mail).one()
    data = Products.query.filter(Products.ref_user.any(user_mail = mail)).filter_by(product_name=prod_name).first()
    return render_template('edit_form.html', data=data, mail=mail)
  
@products_blueprint.route('/update/<string:mail>/<string:prod_name>', methods =['GET','POST'])
@login_required
def update(mail,prod_name):
    if request.method == 'POST':
        p_name = request.form['product_name']
        p_cost = request.form['product_cost']
        p_desc = request.form.get("product_desc")
        prod = Products.query.filter_by(product_name = prod_name).first()
        user = Users.query.filter_by(user_mail = mail).one()
        user.products.remove(prod)
        db.session.delete(prod)
        db.session.commit()
        user = Users.query.filter_by(user_mail = mail).first()
        prod=Products(product_name=p_name, product_cost=p_cost, product_desc=p_desc)
        user.products.append(prod)
        db.session.commit()
        flash("Data Updated Successfully")
        return redirect(url_for('products_route.my_products', mail=mail))

templates/_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"> 
    <title>{{title}}</title>
</head>
<body>
  {% block body %}{% endblock %}
  <nav class="navbar navbar-expand-lg bg-secondary fixed-top">
    <div class="text-center bg-dark text-white">
      <div class="navbar-header">
        <h1 class="text-center"> Welcome to site!</h1>
      </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="/"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
        <li><a href="/login"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </nav>
  {% block content%}
    
  {% endblock%}
    
</body>
</html>

templates/_formhelpers.html
{% macro render_field(field) %}
  <dt>{{ field.label }}
  <dd>{{ field(**kwargs)|safe }}
  {% if field.errors %}
    <ul class=errors>
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  </dd>
{% endmacro %}

templates/_messages.html
{% with messages = get_flashed_messages(with_categories=true) %}
  {% if messages %}
    <ul class=flashes>
    {% for category, message in messages %}
      <li class="alert alert-{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
  {% endif %}
  {% endwith %}

templates/add_product.html
{% from "_formhelpers.html" import render_field %}
<div class="container p-5">
    <h1>Enter Product Details !</h1><br>
    <form action="/add_prod/{{data}}" method="POST">
        {% include '_messages.html' %}
        {{ render_field(form.product_name)}}<br>
        {{ render_field(form.product_cost) }}<br>
        {{ render_field(form.product_desc) }}<br>
        <input type="submit" value="Add Product" class="btn btn-info">

    </form>
</div>

templates/admin_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"> 
    <title>Admin Page</title>
</head>
<body>
    <div class="pull-left">
        <a href="/products" class="btn btn-primary"> View Products </a>
    </div>
    <div class="pull-right">
      <a href="/logout" class="btn btn-danger"> Logout </a>
    </div>
    <div class="container text-center ">  
        <br><h1> Details of all users </h1><br><br>
        <table class="table">
            <th class="text-center"> User Id</th>
            <th class="text-center"> User Name</th>
            <th class="text-center"> User Mail-ID</th>
            <th class="text-center"> Options </th>
          <tbody>
            {%for row in data %}
            <tr>
              <td>{{row.user_id}}</td>
              <td> {{row.user_name}}</td>
              <td> {{row.user_mail}}</td>
              <td> <a href="/remove_user/{{row.user_id}}" class="btn btn-danger"> Remove User </a> </td>
            </tr>
            {%endfor%}
          </tbody>
        </table>
      </div>
</body>
</html>

templates/admin_products.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"> 
    <title>Admin Page</title>
</head>
<body>
  <div class="container text-center">
    <div class="pull-left">
        <a href="/users" class="btn btn-primary"> View Users </a>
    </div>
    <div class="pull-right">
      <a href="/logout" class="btn btn-danger"> Logout </a>
    </div>  
    <br><h1> All Products </h1><br><br>
    <table class="table">
        <th class="text-center"> Product Id</th>
        <th class="text-center"> Product Name</th>
        <th class="text-center"> Product Cost</th>
        <th class="text-center"> Product Description</th>
        <th class="text-center"> </th>
      <tbody>
        {%for row in data%}
        <tr>
          <td>{{row.product_id}}</td>
          <td> {{row.product_name}}</td>
          <td> {{row.product_cost}}</td>
          <td> {{row.product_desc}}</td>
          <td> <a href="/del_prod/{{row.product_id}}" class="btn btn-danger">Delete Product</a> </td>
          </tr>
        {%endfor%}
      </tbody>
    </table>
  </div>
</body>
</html>

templates/display_products.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"> 
  <title>Products</title>
</head>
<body>
  <div class="container text-center ">  
    <div class="pull-right">
      <a href="/logout" class="btn btn-danger"> Logout </a>
    </div>
    <div class="pull-left">
      <a href="/my_prods/{{mail}}" class="btn btn-primary"> My Products </a>
    </div>
    <br><h1> All Products </h1><br><br>
    <table class="table">
        <th class="text-center"> Product Id</th>
        <th class="text-center"> Product Name</th>
        <th class="text-center"> Product Cost</th>
        <th class="text-center"> Product Description</th>
        <th class="text-center"> Cart Button </th>
      <tbody>
        {%for row in data%}
        <tr>
          <td> {{row.product_id}}</td>
          <td> {{row.product_name}}</td>
          <td> {{row.product_cost}}</td>
          <td> {{row.product_desc}}</td>
          <td> <button class="btn btn-success" onclick="return confirm('Successfully added to cart!')"> Add to Cart</button> </td>
        </tr>
        {%endfor%}
      </tbody>
    </table>
  </div>
</body>
</html>

templates/edit_form.html
<div class="container">
    <br><br>
    <h1 class="text-center">Edit Form</h1><br>
    <form action="{{ url_for('products_route.update',mail=mail,prod_name=data.product_name)}}" method="POST">

    <div class="form-group">
        <label> Product Name : </label>
        <input type="text" class="form-control" name="product_name" value="{{data.product_name}}" required="1"/>
    </div>
    <div class="form-group">
        <label> Product Cost : </label>
        <input type="number" class="form-control" name="product_cost" value="{{data.product_cost}}" required="1"/>
    </div>
    <div class="form-group">
      <label> Product Description : </label>
      <input type="text" class="form-control" name="product_desc" value="{{data.product_desc}}" required="1"/>
    </div>
    
    <div class="form-group">
       <button class="btn btn-primary" type="sbumit">Update Product</button>
    </div>
  </form>
</div>

templates/login.html
{% extends '_base.html' %}
{% block content %}
  {% from "_formhelpers.html" import render_field %}
    <form action="/login" method="POST">
    <div class="col-md-4">
      {% include '_messages.html' %}
      {{ render_field(form.user_mail) }}<br>
      {{ render_field(form.user_paswd) }}

      <br>
    <p><input type="submit" value="Login" class="btn btn-info">
    </div>
  </form>
{% endblock %}

templates/product_options.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css"> 
  <title>Products</title>
</head>
<body>
  <div class="container text-center"> 
    <div class="pull-right">
      <a href="/logout" class="btn btn-danger"> Logout </a>
    </div>
    <div class="pull-left">
      <a href="/all_products/{{mail}}" class="btn btn-primary">All Products</a>
    </div>
      {% include '_messages.html' %}
      <br><h1> Products List </h1><br><br>
      <table class="table">
        <th class="text-center"> Product Name</th>
        <th class="text-center"> Product Cost</th>
        <th class="text-center"> Product Description</th>
        <th class="text-center"> Options </th>
      <tbody>
        {%for row in data%}
        <tr>
          <td>{{row.product_name}}</td>
          <td> {{row.product_cost}}</td>
          <td> {{row.product_desc}}</td>
          <td><a href="{{url_for('products_route.edit', mail=mail, prod_name=row.product_name)}}" class="btn btn-danger" data-toggle="modal" data-target="#modaledit{{row.0}}">Edit</a>
          <a href= "{{url_for('products_route.delete', mail=mail, prod_name=row.product_name)}}" class="btn btn-danger" onclick="return confirm('Are you sure to delete it ?')">Delete</a>
          </td></tr>
        {%endfor%}
      </tbody>
      </table>
      <div class="container">
        <a href="/add_prod/{{mail}}" class="btn btn-primary">Add New Product</a>
      </div>
  </div>
  
</body>
</html>

templates/signup.html
{% extends '_base.html' %}
{% block content %}
  {% from "_formhelpers.html" import render_field %}
    <form action="" method="POST">
    <div class="container">
      {% include '_messages.html' %}
      {{ render_field(form.user_name, class="form-control ")}}<br>
      {{ render_field(form.user_mail, class="form-control") }}<br>
      {{ render_field(form.user_paswd,class="form-control")}}<br>
      {{ render_field(form.confirm, class="form-control") }}
      <br>
      <input type="submit" value="Sign Up" class="btn btn-info">
    </div>
  </form>
{% endblock %}